name: Publish NuGet package

on:
  push:
    branches: [ main ]

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'

    - name: Copy readme.md to project folder
      run: cp readme.md src/ToJsonExtensions/readme.md



    - name: Restore dependencies
      run: dotnet restore src/ToJsonExtensions

    - name: Build
      run: dotnet build src/ToJsonExtensions --configuration Release

    - name: Pack
      run: dotnet pack src/ToJsonExtensions --configuration Release --output ./nupkgs

    - name: Push to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
